export const Users = [
  {
    id:1,
    profilePicture: "person/steve-rogers.jpg",
    username: "Steve Rogers",
  },
  {
    id:2,
    profilePicture: "person/tony-stark.jpg",
    username: "Tony Stark",
  },
  {
    id:3,
    profilePicture: "person/natasha-romanoff.jpg",
    username: "Natasha Romanoff",
  },
  {
    id:4,
    profilePicture: "person/thor.jpg",
    username: "Thor",
  },
  {
    id:5,
    profilePicture: "person/loki.jpg",
    username: "Loki",
  },
  {
    id:6,
    profilePicture: "person/nick-fury.jpg",
    username: "Nick Fury",
  },
  {
    id:7,
    profilePicture: "person/peter-parker.jpg",
    username: "Peter Parker",
  },
  {
    id:8,
    profilePicture: "person/bruce-banner.jpg",
    username: "Dr. Bruce Banner",
  },
  {
    id:9,
    profilePicture: "person/doctor-strange.jpg",
    username: "Doctor Strange",
  },
  {
    id:10,
    profilePicture: "person/king-t'challa.jpg",
    username: "King T'Challa",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.jpeg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
